name = "VLDataScienceMachineLearningPackage"
uuid = "24b76065-2c22-4f73-af85-7cb67476fb03"
version = "0.1.0"
authors = ["Jeffrey Varner <jdv27@cornell.edu>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSV = "0.10.15"
ColorVectorSpace = "0.11.0"
DataFrames = "1.7.0"
DataStructures = "0.18.22, 0.19"
Distributions = "0.25.120"
FileIO = "1.17.0"
GLPK = "1.2.1"
JSON = "0.21.4, 1"
JuMP = "1.29.1"
LinearAlgebra = "1.11.0"
MadNLP = "0.8.12"
Statistics = "1.11.1"
Test = "1.11.0"
